# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180722_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='image',
        ),
    ]
