# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180722_1442'),
        ('feed', '0002_auto_20180722_1431'),
    ]

    operations = [
    ]
