# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_headline_image'),
        ('feed', '0003_merge_20180722_1619'),
    ]

    operations = [
    ]
