# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20180725_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timesofindiadb',
            new_name='NDTVdb',
        ),
    ]
