# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_indiatimesdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndiaTimesdb',
        ),
        migrations.RemoveField(
            model_name='indiatvdb',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='ndtvdb',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='republicdb',
            name='published_date',
        ),
        migrations.AddField(
            model_name='indiatvdb',
            name='href',
            field=models.CharField(default='2', max_length=600),
        ),
        migrations.AddField(
            model_name='ndtvdb',
            name='href',
            field=models.CharField(default='2', max_length=600),
        ),
        migrations.AddField(
            model_name='republicdb',
            name='href',
            field=models.CharField(default='2', max_length=600),
        ),
    ]
