# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20180731_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indiatvdb',
            new_name='Hindustan_db',
        ),
    ]
